apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml

secretGenerator:
  - name: $APP_NAME-api-properties
    namespace: $NAMESPACE
    files:
      - application-live.properties